version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "jnlp-lambdas-sam"
s3_bucket = "lambda-cloud-bucket"
# s3_prefix = "jnlp-lambdas"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
tags = "type=jnlp-agent"
