# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: iliyankostov
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: jenkins
service: jnlp-lambdas

provider:
  name: aws
  region: ${opt:region, env:AWS_REGION, 'eu-west-1'}
  stage: ${self:custom.stage}
  deploymentBucket:
    blockPublicAccess: true
  timeout: 900 # could be set to the max of 900s (15 mins)
  logRetentionInDays: 7
  environment:
    HOME_DIR: "/tmp"
  tags:
    type: jnlp-agent

custom:
  stage: ${opt:stage, env:STAGE, 'v1'}

package:
  artifact: lambda/target/agent-dev.jar

functions:
  agentGitBash:
    name: jnlp-agent-git-bash
    handler: io.jenkins.agent.aws.lambda.AgentHandler
    runtime: java11
    memorySize: 3008
    layers:
      - arn:aws:lambda:${self:provider.region}:744348701589:layer:bash:8
      - arn:aws:lambda:${self:provider.region}:553035198032:layer:git-lambda2:4
  agentGitBashNode:
    name: jnlp-agent-git-bash-node
    handler: io.jenkins.agent.aws.lambda.AgentHandler
    runtime: java11
    memorySize: 3008
    layers:
      - arn:aws:lambda:${self:provider.region}:744348701589:layer:bash:8
      - arn:aws:lambda:${self:provider.region}:553035198032:layer:git-lambda2:4
      # https://github.com/lambci/node-custom-lambda#current-version-arns
      - arn:aws:lambda:${self:provider.region}:553035198032:layer:nodejs12:26
