name: deploy_AWS_resources
description: "Deploy Terraform After Infra"
inputs:
  app:
    description: |
      App to be deployed on 12 months free.
      - passbolt
    required: true
    type: string

    env:
      terraform_main_file_path: "./terraform/apps/12_months_free/${{ inputs.app }}"
      terraform_var_file: |
        "-var-file=./terraform/envs/prod/common/env.tfvars -var-file=./terraform/envs/prod/app/12_months_free/passbolt/env.tfvars"

runs:
  using: "composite"
  steps:
    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Run Terraform init
    # Setup connection to Azure + setup backend to use SA where we store Statefile
    - name: Terraform Init
      id: init
      shell: pwsh
      run: | # Folded Block Scalar ">" which converts new lines into spaces
        terraform -chdir="${{ terraform_main_file_path }}" init"

    # Run a Terraform validate
    - name: Terraform validate
      id: validate
      if: success() || failure()
      shell: pwsh
      run: terraform validate -no-color

    # Run a Terraform plan
    - name: Terraform plan
      id: plan
      shell: pwsh
      run: terraform -chdir=${{ terraform_main_file_path }} plan -no-color -input=false ${{ terraform_var_file }}"

    # Run a Terraform apply
    - name: Terraform apply
      id: apply
      if: success()
      shell: pwsh
      run: terraform -chdir=${{ inputs.pathTfMain }} apply -auto-approve -input=false ${{ terraform_var_file }}"
