name: Terraform workflow

on:
  push:
    branches:
      - master
    paths:
      - infra/**
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform job
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        app: ["domain", "vpn"]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_SOPHIA_AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_SOPHIA_AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Age
        uses: AnimMouse/setup-age@d7fa8779bcb38294334a3aa753c7171e8da5067e # v1.2

      - name: Decrypt terraform.tfvars
        run: |
          cd infra/env/prod/${{ matrix.app }}
          echo "$AGE_KEY" > /tmp/age-key.txt
          age --decrypt -i /tmp/age-key.txt terraform.tfvars.age > terraform.tfvars
          rm /tmp/age-key.txt
        env:
          AGE_KEY: ${{ secrets.PORTFOLIO_AGE_KEY }}

      - name: Setup terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e #v4
        with:
          terraform_version: "1.9"

      - name: Initialize
        run: make tf-init APP_NAME=${{ matrix.app }}

      - name: Validate
        if: success() || failure()
        run: make tf-validate APP_NAME=${{ matrix.app }}

      - name: Plan
        run: make tf-plan APP_NAME=${{ matrix.app }}

      - name: Apply
        run: make tf-apply APP_NAME=${{ matrix.app }}
