name: Terraform_deploy_AWS_12_free_months
#description: "Deploy Terraform After Infra"

on:
  push:
    branches:
      - none

  workflow_dispatch:
    inputs:
      app:
        type: choice
        description: |
          App to be deployed on 12 months free.
        options:
          - passbolt
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    if: github.repository != 'hashicorp-education/learn-terraform-github-actions'
    name: "Terraform Plan"
    permissions:
      contents: read
      pull-requests: write

    env:
      terraform_main_file_path: "terraform/apps/12_months_free/${{ inputs.app }}"
      terraform_var_common_file: "../../../envs/prod/common/env.tfvars"
      terraform_var_app_file: "../../../envs/prod/app/12_months_free/${{ inputs.app }}/env.tfvars"
      # Terraform secrets
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_ORG }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_WORKSPACE: "github-aws-account-creation-actions-workspace"
      CONFIG_DIRECTORY: "./"
      # runs:
      #   using: "composite"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: plan-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.terraform_main_file_path }}
          speculative: true

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Run Terraform init
      # Setup connection to Azure + setup backend to use SA where we store Statefile
      - name: Terraform Init
        id: init
        shell: bash
        run: | # Folded Block Scalar ">" which converts new lines into spaces
          terraform -chdir=${{ env.terraform_main_file_path }} init

      # Run a Terraform validate
      - name: Terraform validate
        id: validate
        if: success() || failure()
        shell: bash
        run: terraform validate -no-color

      # Run a Terraform plan
      - name: Terraform plan
        id: plan
        shell: bash
        run: |
          terraform -chdir="${{ env.terraform_main_file_path }}" plan \
            -no-color \
            -input=false \
            -var-file="${{ env.terraform_var_common_file }}" \
            -var-file="${{ env.terraform_var_app_file }}"

      # Run a Terraform apply
      - name: Terraform apply
        id: apply
        if: success()
        shell: bash
        run: |
          terraform -chdir="${{ env.terraform_main_file_path }}" \
          apply \
          -auto-approve \
          -input=false \
          -var-file=${{ env.terraform_var_common_file }} \
          -var-file=${{ env.terraform_var_app_file }}"
